from flask import Blueprint, request, jsonify, current_app
from app.models import User
from app.utils.auth import create_jwt, auth_required, decode_jwt, verify_telegram_login
from app import get_db
import requests
import os

auth_bp = Blueprint('auth', __name__)

BIFROST_URL = os.getenv("BIFROST_URL", "http://bifrost:5000")
BIFROST_CLIENT_ID = os.getenv("BIFROST_CLIENT_ID")
BIFROST_CLIENT_SECRET = os.getenv("BIFROST_CLIENT_SECRET")

# --- WEB AUTHENTICATION (Case 2) ---

@auth_bp.route('/register', methods=['POST'])
def register():
    data = request.get_json()
    email = data.get('email')
    password = data.get('password')

    if not email or not password:
        return jsonify({"error": "Email and password required"}), 400

    existing = User.find_by_email(email)
    if existing:
        return jsonify({"error": "Email already exists"}), 409

    user = User.create_from_email(email, password)
    token = create_jwt(str(user['_id']), user.get('roles', ['user']))

    return jsonify({
        "message": "Registration successful",
        "token": token,
        "user": {
            "id": str(user['_id']),
            "email": user['email'],
            "onboarding_complete": False
        }
    }), 201

@auth_bp.route('/login', methods=['POST'])
def login():
    data = request.get_json()
    email = data.get('email')
    password = data.get('password')

    user = User.find_by_email(email)
    if user and User.verify_password(user, password):
        token = create_jwt(str(user['_id']), user.get('roles', ['user']))

        # Check onboarding status
        profile = get_db().settings.find_one({"account_id": user['_id']})
        onboarding = profile.get('onboarding_complete', False) if profile else False

        return jsonify({
            "token": token,
            "user": {
                "id": str(user['_id']),
                "email": user['email'],
                "telegram_connected": bool(user.get('telegram_id')),
                "onboarding_complete": onboarding
            }
        }), 200

    return jsonify({"error": "Invalid credentials"}), 401

# --- TELEGRAM -> WEB LOGIN (Case 1) ---

@auth_bp.route('/verify-otp', methods=['POST'])
def verify_otp():
    """
    Validates the 6-digit code generated by the Telegram Bot via Bifrost.
    If valid, logs the user into the Web App.
    """
    data = request.get_json()
    code = data.get('code')

    if not code:
        return jsonify({"error": "Code required"}), 400

    # 1. Verify Code with Bifrost
    try:
        res = requests.post(
            f"{BIFROST_URL}/internal/verify-otp",
            json={"code": code},
            auth=(BIFROST_CLIENT_ID, BIFROST_CLIENT_SECRET),
            timeout=5
        )
        res.raise_for_status()
        bifrost_data = res.json()

        if not bifrost_data.get('valid'):
            return jsonify({"error": "Invalid or expired code"}), 401

        telegram_id = bifrost_data.get('telegram_id')

    except Exception as e:
        current_app.logger.error(f"Bifrost OTP verify failed: {e}")
        return jsonify({"error": "Verification service unavailable"}), 503

    # 2. Find or Create User
    user = User.find_by_telegram_id(telegram_id)
    if not user:
        # If user generated a code, they exist in Telegram, so we should sync.
        user = User.create_from_telegram(telegram_id, "Unknown")

    # 3. Generate Web Token
    token = create_jwt(str(user['_id']), user.get('roles', ['user']))

    profile = get_db().settings.find_one({"account_id": user['_id']})
    onboarding = profile.get('onboarding_complete', False) if profile else False

    return jsonify({
        "message": "Login successful",
        "token": token,
        "user": {
            "id": str(user['_id']),
            "telegram_id": telegram_id,
            "email_connected": bool(user.get('email')),
            "onboarding_complete": onboarding
        }
    }), 200

# --- ACCOUNT LINKING ---

@auth_bp.route('/link-account', methods=['POST'])
@auth_required
def link_account(user_id):
    """
    Links credentials to the current account.
    - 'email' + 'password': Connect Email to a Telegram-only account.
    - 'telegram_data': Connect Telegram Widget data to a Web-only account.
    """
    data = request.get_json()

    # 1. Link Email (Case 1: Tele User adding Email Login)
    if 'email' in data and 'password' in data:
        success, msg = User.link_email(user_id, data['email'], data['password'])
        if success:
            return jsonify({"message": "Email linked successfully"}), 200
        return jsonify({"error": msg}), 400

    # 2. Link Telegram (Case 2: Web User linking Tele via Widget)
    if 'telegram_data' in data:
        tg_data = data['telegram_data']

        # A. Security Check
        bot_token = current_app.config.get('TELEGRAM_TOKEN')
        if not bot_token:
            current_app.logger.error("TELEGRAM_TOKEN missing in config, cannot verify hash.")
            return jsonify({"error": "Server misconfiguration"}), 500

        if not verify_telegram_login(tg_data, bot_token):
            current_app.logger.warning(f"Telegram hash verification failed for user {user_id}")
            return jsonify({"error": "Invalid Telegram verification data"}), 401

        # B. Link
        telegram_id = tg_data.get('id')
        info = {
            'first_name': tg_data.get('first_name'),
            'username': tg_data.get('username')
        }

        success, msg = User.link_telegram(user_id, telegram_id, info)
        if success:
            return jsonify({"message": "Telegram linked successfully"}), 200
        return jsonify({"error": msg}), 400

    return jsonify({"error": "Invalid data format"}), 400

# --- BOT SYNC (Existing Flow) ---

@auth_bp.route('/sync-session', methods=['POST'])
def sync_session():
    """
    Called by Telegram Bot. Receives a Bifrost JWT, validates it,
    and ensures a User/Profile exists in Finance DB.
    """
    auth_header = request.headers.get('Authorization')
    if not auth_header:
        return jsonify({"error": "Missing token"}), 401

    token = auth_header.split(" ")[1]

    # 1. Decode Bifrost Token to get Telegram ID
    try:
        decoded = decode_jwt(token)
        # Note: decode_jwt usually verifies signature if secret is correct
        # Ensure we are using the correct secret that Bifrost signed with.
    except:
        return jsonify({"error": "Invalid token"}), 401

    tg_id = decoded.get('telegram_id') or decoded.get('sub')
    if not tg_id:
        return jsonify({"error": "Token missing identity"}), 400

    # 2. Find or Create User
    user = User.find_by_telegram_id(tg_id)
    if not user:
        first_name = decoded.get('first_name', 'User')
        username = decoded.get('username')
        user = User.create_from_telegram(tg_id, first_name, username)

    return jsonify({
        "status": "synchronized",
        "user_id": str(user['_id']),
        "is_premium": User.is_premium(user['_id'])
    }), 200